# exercise 

In [1]:
import numpy as np

# 1. Create a 1D NumPy array containing the integers from 0 to 9.
array_1d = np.arange(10)
print("1D array:", array_1d)

# 2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20.
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D array:\n", array_2d)

# 3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
array_3d = np.ones((2, 3, 4))
print("3D array:\n", array_3d)

# 4. Add two 1D arrays element-wise.
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
sum_arrays = np.add(array1, array2)
print("Element-wise sum of 1D arrays:", sum_arrays)

# 5. Multiply two 2D arrays element-wise.
array2d_1 = np.random.randint(1, 10, size=(3, 3))
array2d_2 = np.random.randint(1, 10, size=(3, 3))
product_arrays = np.multiply(array2d_1, array2d_2)
print("Element-wise product of 2D arrays:\n", product_arrays)

# 6. Calculate the dot product of two matrices.
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))
dot_product = np.dot(matrix1, matrix2)
print("Dot product of matrices:\n", dot_product)

# 7. Calculate the mean, median, and standard deviation of a 1D array.
mean_val = np.mean(array_1d)
median_val = np.median(array_1d)
std_dev = np.std(array_1d)
print(f"Mean: {mean_val}, Median: {median_val}, Standard Deviation: {std_dev}")

# 8. Find the maximum and minimum values in a 2D array.
max_val = np.max(array_2d)
min_val = np.min(array_2d)
print(f"Maximum value in 2D array: {max_val}, Minimum value in 2D array: {min_val}")

# 9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
normal_dist_array = np.random.normal(0, 1, 1000)
print("Array of 1000 random numbers from normal distribution ", normal_dist_array[:10])

# 10. Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.
uniform_dist_array = np.random.randint(10, 51, size=(5, 5))
print("2D array of random integers from uniform distribution:\n", uniform_dist_array)

# 11. Calculate the cumulative sum of a 1D array.
cumulative_sum = np.cumsum(array_1d)
print("Cumulative sum of 1D array:", cumulative_sum)

# 12. Compute the correlation coefficient matrix of a 2D array.
correlation_matrix = np.corrcoef(uniform_dist_array)
print("Correlation coefficient matrix of 2D array:\n", correlation_matrix)

# 13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
die_rolls = np.random.randint(1, 7, 1000)
frequency = np.bincount(die_rolls)[1:]
print("Frequency of each outcome in 1000 die rolls:", frequency)


1D array: [0 1 2 3 4 5 6 7 8 9]
2D array:
 [[ 4  1 15]
 [ 5  7  9]
 [ 2 13  5]]
3D array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Element-wise sum of 1D arrays: [ 6  8 10 12]
Element-wise product of 2D arrays:
 [[42 36  6]
 [ 9 36  6]
 [54 72 81]]
Dot product of matrices:
 [[ 94  54 124]
 [ 98  48 113]
 [ 51  30  53]]
Mean: 4.5, Median: 4.5, Standard Deviation: 2.8722813232690143
Maximum value in 2D array: 15, Minimum value in 2D array: 1
Array of 1000 random numbers from normal distribution (first 10 values): [ 1.07801684 -0.11236798 -1.73971408 -0.72115511 -0.74472431 -2.13342157
 -0.8738014   1.66837244  1.70875431  0.51008345]
2D array of random integers from uniform distribution:
 [[11 18 27 43 50]
 [26 45 23 23 13]
 [13 44 33 19 19]
 [13 29 43 25 16]
 [29 28 28 42 18]]
Cumulative sum of 1D array: [ 0  1  3  6 10 15 21 28 36 45]
Correlation coefficient matrix of 2D array:
 [[ 1.         -0.6724583  -0.26612465 -0.0687956

# Example problems 

In [2]:
import numpy as np

data = np.array([20, 25, 15, 5, 18, 55, 33, 38, 22, 10])

mean = np.mean(data)
std_dev = np.std(data)

z_scores = (data - mean) / std_dev

print("Original Data:", data)
print("Z-scores:", z_scores)


Original Data: [20 25 15  5 18 55 33 38 22 10]
Z-scores: [-0.29490298  0.0647348  -0.65454076 -1.37381633 -0.43875809  2.2225615
  0.64015525  0.99979304 -0.15104787 -1.01417855]


# Z score for normal distribution

In [3]:
import numpy as np

np.random.seed(0) 
data_normal = np.random.normal(loc=50, scale=10, size=100)

mean_normal = np.mean(data_normal)
std_dev_normal = np.std(data_normal)

z_scores_normal = (data_normal - mean_normal) / std_dev_normal

print("Original Data (first 10 elements):", data_normal[:10])
print("Z-scores (first 10 elements):", z_scores_normal[:10])


Original Data (first 10 elements): [67.64052346 54.00157208 59.78737984 72.40893199 68.6755799  40.2272212
 59.50088418 48.48642792 48.96781148 54.10598502]
Z-scores (first 10 elements): [ 1.69091612  0.33768746  0.91174338  2.16402779  1.79361228 -1.02897526
  0.88331787 -0.20951378 -0.1617519   0.34804709]


# Percentiles 

In [4]:
data_percentiles = np.random.randint(low=0, high=100, size=50)

percentile_25 = np.percentile(data_percentiles, 25)
median = np.percentile(data_percentiles, 50)
percentile_75 = np.percentile(data_percentiles, 75)

print("Original Data (first 10 elements):", data_percentiles[:10])
print(f"25th Percentile: {percentile_25}")
print(f"Median (50th Percentile): {median}")
print(f"75th Percentile: {percentile_75}")


Original Data (first 10 elements): [32 70 85 31 13 71 56 24 79 41]
25th Percentile: 27.25
Median (50th Percentile): 45.0
75th Percentile: 74.75


# 2d arrays

In [5]:
import numpy as np


arr_2d = np.random.randint(low=1, high=20, size=(3, 3))
print("2D Array:")
print(arr_2d)
print()
print("Element at (0, 0):", arr_2d[0, 0])
print("Element at (1, 2):", arr_2d[1, 2])
print()
print("First row:", arr_2d[0])
print("Second column:", arr_2d[:, 1])
print("Subarray (first two rows, last two columns):")
print(arr_2d[:2, -2:])
print()
arr_2d_2 = np.random.randint(low=1, high=20, size=(3, 3))
print("Second 2D Array:")
print(arr_2d_2)
print()
print("Element-wise addition:")
print(arr_2d + arr_2d_2)
print()
print("Element-wise multiplication:")
print(arr_2d * arr_2d_2)
print()
matrix_mult = np.dot(arr_2d, arr_2d_2)
print("Matrix multiplication (dot product):")
print(matrix_mult)


2D Array:
[[ 4  4  8]
 [10 10 10]
 [ 4 15 19]]

Element at (0, 0): 4
Element at (1, 2): 10

First row: [4 4 8]
Second column: [ 4 10 15]
Subarray (first two rows, last two columns):
[[ 4  8]
 [10 10]]

Second 2D Array:
[[13  4 10]
 [11 14  8]
 [ 8  2 13]]

Element-wise addition:
[[17  8 18]
 [21 24 18]
 [12 17 32]]

Element-wise multiplication:
[[ 52  16  80]
 [110 140  80]
 [ 32  30 247]]

Matrix multiplication (dot product):
[[160  88 176]
 [320 200 310]
 [369 264 407]]


# Rotation in arrays 

In [6]:
import numpy as np

def rotate_anticlockwise(matrix):
    
    arr = np.array(matrix)
    transposed = np.transpose(arr)
    rotated = np.flip(transposed, axis=1)
    
    return rotated.tolist()  


matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
for row in matrix:
    print(row)

rotated_matrix = rotate_anticlockwise(matrix)

print("\nAnticlockwise Rotated Matrix:")
for row in rotated_matrix:
    print(row)


Original Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Anticlockwise Rotated Matrix:
[7, 4, 1]
[8, 5, 2]
[9, 6, 3]
