# Matrix Creation and Manipulation

In [2]:
import numpy as np
import scipy.linalg

# Zero matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

# Identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Random matrix
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[0.19130988 0.45709545 0.20905195]
 [0.48431562 0.57480901 0.63324974]
 [0.99373803 0.43505123 0.86987815]]


# basic matrix operations

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
addition = A + B
print("Matrix Addition:\n", addition)

# Subtraction
subtraction = A - B
print("Matrix Subtraction:\n", subtraction)

# Multiplication (element-wise)
multiplication_elementwise = A * B
print("Element-wise Multiplication:\n", multiplication_elementwise)

# Matrix Multiplication
multiplication_matrix = np.dot(A, B)
print("Matrix Multiplication:\n", multiplication_matrix)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


# Transpose

In [3]:
A_transpose = A.T
print("Transpose of A:\n", A_transpose)

# Determinant of a matrix
determinant_A = np.linalg.det(A)
print("Determinant of A:", determinant_A)

# Inverse of a matrix
A_inverse = np.linalg.inv(A)
print("Inverse of A:\n", A_inverse)


Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Linear eqs

In [4]:
# Ax = B
A = np.array([[2, 3], [1, -2]])
B = np.array([8, -4])
x = np.linalg.solve(A, B)
print("Solution x:", x)


Solution x: [0.57142857 2.28571429]


# LU decomposition, QR decomposition

In [9]:
# LU Decomposition
P, L, U = scipy.linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

# QR Decomposition
Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)


P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.  0. ]
 [0.5 1. ]]
U:
 [[ 2.   3. ]
 [ 0.  -3.5]]
Q:
 [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
R:
 [[-2.23606798 -1.78885438]
 [ 0.         -3.13049517]]


# Eigen Values

In [6]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Verify by reconstructing the original matrix
reconstructed_matrix = np.dot(np.dot(eigenvectors, np.diag(eigenvalues)), np.linalg.inv(eigenvectors))
print("Reconstructed Matrix:\n", reconstructed_matrix)


Eigenvalues: [ 2.64575131 -2.64575131]
Eigenvectors:
 [[ 0.97760877 -0.54247681]
 [ 0.21043072  0.84007078]]
Reconstructed Matrix:
 [[ 2.  3.]
 [ 1. -2.]]


# Vector Operations

In [7]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
vector_addition = v1 + v2
print("Vector Addition:", vector_addition)

# Dot Product
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

# Cross Product
cross_product = np.cross(v1, v2)
print("Cross Product:", cross_product)

# Normalize a vector
norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print("Normalized v1:", normalized_v1)


Vector Addition: [5 7 9]
Dot Product: 32
Cross Product: [-3  6 -3]
Normalized v1: [0.26726124 0.53452248 0.80178373]


# Principal Component Analysis (PCA)

is a method used to reduce the dimensionality of a dataset by transforming it into a new set of variables, the principal components, which are orthogonal and capture the maximum variance in the data

In [3]:
def standardize(X):
    return (X - np.mean(X, axis=0)) / np.std(X, axis=0)

def pca_svd(X, n_components):
    # Standardize the dataset
    X_std = standardize(X)

    # Compute the covariance matrix
    covariance_matrix = np.cov(X_std.T)

    # Perform SVD
    U, S, Vt = np.linalg.svd(covariance_matrix)

    # Select the top n_components
    principal_components = Vt[:n_components]

    # Transform the original dataset
    X_pca = X_std.dot(principal_components.T)

    return X_pca, principal_components

X = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0], [2.3, 2.7], [2, 1.6], [1, 1.1], [1.5, 1.6], [1.1, 0.9]])
n_components = 1
X_pca, principal_components = pca_svd(X, n_components)
print("Transformed dataset:\n", X_pca)
print("Principal components:\n", principal_components)


Transformed dataset:
 [[-1.08643242]
 [ 2.3089372 ]
 [-1.24191895]
 [-0.34078247]
 [-2.18429003]
 [-1.16073946]
 [ 0.09260467]
 [ 1.48210777]
 [ 0.56722643]
 [ 1.56328726]]
Principal components:
 [[-0.70710678 -0.70710678]]


# Numerical Differentiation

**Numerical differentiation is the process of estimating the derivative of a function using numerical methods.**

Forward, Backward, and Central Difference Methods:
Forward Difference:
𝑓
′
(
𝑥
)
≈
𝑓
(
𝑥
+
ℎ
)
−
𝑓
(
𝑥
)
ℎ
f
′
 (x)≈
h
f(x+h)−f(x)
​

Backward Difference:
𝑓
′
(
𝑥
)
≈
𝑓
(
𝑥
)
−
𝑓
(
𝑥
−
ℎ
)
ℎ
f
′
 (x)≈
h
f(x)−f(x−h)
​

Central Difference:
𝑓
′
(
𝑥
)
≈
𝑓
(
𝑥
+
ℎ
)
−
𝑓
(
𝑥
−
ℎ
)
2
ℎ
f
′
 (x)≈
2h
f(x+h)−f(x−h)
​


In [4]:
def forward_difference(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

def backward_difference(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

def central_difference(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)


f = lambda x: x**2
x = 2
print("Forward difference:", forward_difference(f, x))
print("Backward difference:", backward_difference(f, x))
print("Central difference:", central_difference(f, x))


Forward difference: 4.000010000027032
Backward difference: 3.999990000025377
Central difference: 4.000000000026205


# Numerical Integration

**Numerical integration approximates the integral of a function over a specified interval. This is useful when the integral is difficult or impossible to calculate analytically.**

In [5]:
def trapezoidal_rule(f, a, b, n=1000):
    x = np.linspace(a, b, n)
    y = f(x)
    h = (b - a) / (n - 1)
    return (h / 2) * np.sum(y[:-1] + y[1:])
    # Approximates the area under the curve by dividing it into trapezoids.

def simpsons_rule(f, a, b, n=1000):
    if n % 2 == 1:
        n += 1
    x = np.linspace(a, b, n)
    y = f(x)
    h = (b - a) / (n - 1)
    return (h / 3) * (y[0] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]) + y[-1])
    # Approximates the area under the curve using parabolas.


f = lambda x: x**2
a, b = 0, 1
print("Trapezoidal rule:", trapezoidal_rule(f, a, b))
print("Simpson's rule:", simpsons_rule(f, a, b))


Trapezoidal rule: 0.33333350033383397
Simpson's rule: 0.33233400166866833


# Partial derivatives

**Partial derivatives measure the rate at which a multivariable function changes as one of the variables changes, holding the others constant.**

In [6]:
def partial_derivative(f, x, y, var='x', h=1e-5):
    if var == 'x':
        return (f(x + h, y) - f(x - h, y)) / (2 * h)
    elif var == 'y':
        return (f(x, y + h) - f(x, y - h)) / (2 * h)


f = lambda x, y: x**2 + y**2
x, y = 1, 2
print("Partial derivative w.r.t x:", partial_derivative(f, x, y, var='x'))
print("Partial derivative w.r.t y:", partial_derivative(f, x, y, var='y'))


Partial derivative w.r.t x: 2.0000000000131024
Partial derivative w.r.t y: 4.000000000026205


# Optimization
**Optimization involves finding the maximum or minimum of a function subject to constraints.**



In [7]:
from scipy.optimize import minimize

def objective_function(x):
    return x[0]**2 + x[1]**2

def constraint1(x):
    return x[0] + x[1] - 1  # x0 + x1 = 1

# Define constraints
cons = {'type': 'eq', 'fun': constraint1}

# Initial guess
x0 = [0.5, 0.5]

# Solve optimization problem
result = minimize(objective_function, x0, constraints=cons)

print("Optimal solution:", result.x)


Optimal solution: [0.5 0.5]
