# **Numpy advanced **

In [9]:
import numpy as np

# Task 1: Extract a 3x3 sub-array starting from the element at position (1, 1)
array_2d = np.arange(25).reshape(5, 5)
sub_array_3x3 = array_2d[1:4, 1:4]
print("Task 1\n3x3 sub-array starting from (1,1):\n", sub_array_3x3)

# Task 2: Extract all elements in the first two rows and all columns of the second slice along the third axis from a 3D array
array_3d = np.arange(24).reshape(4, 3, 2)
sub_array_3d = array_3d[:2, :, 1]
print("Task 2\nElements from first two rows, all columns of second slice:\n", sub_array_3d)

# Task 3: Use fancy indexing to extract elements at positions [1, 3, 4, 7]
array_int = np.arange(10)
fancy_indexed = array_int[[1, 3, 4, 7]]
print("Task 3\nElements at positions [1, 3, 4, 7]:\n", fancy_indexed)

# Task 4: Use fancy indexing to select rows [0, 2, 3] and columns [1, 3]
array_2d_fancy = np.arange(25).reshape(5, 5)
fancy_rows_cols = array_2d_fancy[[0, 2, 3], :][:, [1, 3]]
print("Task 4\nRows [0, 2, 3] and columns [1, 3]:\n", fancy_rows_cols)

# Task 5: Extract all elements greater than 10 from a 1D array of random integers
random_integers = np.random.randint(0, 20, size=15)
greater_than_10 = random_integers[random_integers > 10]
print("Task 5\nElements greater than 10:\n", greater_than_10)

# Task 6: Replace all elements greater than 15 with 0 in a 2D array of shape (5, 5)
array_2d_replace = np.arange(25).reshape(5, 5)
array_2d_replace[array_2d_replace > 15] = 0
print("Task 6\nArray with elements > 15 replaced by 0:\n", array_2d_replace)

# Task 7: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)
array_2d_broadcast = np.ones((4, 3))
array_1d = np.array([1, 2, 3])
broadcasted_sum = array_2d_broadcast + array_1d
print("Task 7\nBroadcasted sum:\n", broadcasted_sum)

# Task 8: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
array_2d_mult = np.ones((3, 3)) * 2
array_1d_mult = np.array([1, 2, 3])
broadcasted_product = array_2d_mult * array_1d_mult
print("Task 8\nBroadcasted product:\n", broadcasted_product)

# Task 9: Perform element-wise addition of two 2D arrays of shapes (3, 1) and (1, 4)
array_2d_3x1 = np.array([[1], [2], [3]])
array_2d_1x4 = np.array([[4, 5, 6, 7]])
elementwise_sum = array_2d_3x1 + array_2d_1x4
print("Task 9\nElement-wise addition:\n", elementwise_sum)

# Task 10: Add a 2D array of shape (3, 4) to each 2D slice along the first axis of a 3D array of shape (2, 3, 4)
array_3d_broadcast = np.ones((2, 3, 4))
array_2d_broadcast = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
broadcasted_sum_3d = array_3d_broadcast + array_2d_broadcast
print("Task 10\nBroadcasted sum on 3D array:\n", broadcasted_sum_3d)

# Task 11: Extract every second row and column from a 2D array, then add a 1D array to each row of the sliced array
array_2d_slice = np.arange(25).reshape(5, 5)
sliced_array = array_2d_slice[::2, ::2]
array_1d_add = np.array([1, 2, 3])
sliced_and_added = sliced_array + array_1d_add[:sliced_array.shape[1]]
print("Task 11\nEvery second row and column, added 1D array:\n", sliced_and_added)

# Task 12: Extract a sub-array from a 3D array and subtract a 2D array from each slice along the third axis using broadcasting
array_3d_slice = np.arange(24).reshape(4, 3, 2)
sub_array_3d_slice = array_3d_slice[:2, :, :]
array_2d_subtract = np.array([[1, 1], [2, 2], [3, 3]])
broadcasted_subtract = sub_array_3d_slice - array_2d_subtract[:, :, np.newaxis]
print("Task 12\nBroadcasted subtraction:\n", broadcasted_subtract)

# Task 13: Extract the diagonal elements from a 2D array and create a 1D array
array_2d_diag = np.arange(16).reshape(4, 4)
diagonal_elements = np.diag(array_2d_diag)
print("Task 13\nDiagonal elements:\n", diagonal_elements)

# Task 14: Reverse the order of elements in each row of a 2D array using slicing
array_2d_reverse = np.arange(16).reshape(4, 4)
reversed_array = array_2d_reverse[:, ::-1]
print("Task 14\nReversed rows:\n", reversed_array)

# Task 15: Extract a sub-array of shape (2, 3, 4) from a 3D array and add a 1D array of shape (4,) to each row along the third axis using broadcasting
array_3d_large = np.arange(120).reshape(4, 5, 6)
sub_array_3d_large = array_3d_large[:2, :3, :4]
array_1d_add_large = np.array([1, 2, 3, 4])
broadcasted_sum_large = sub_array_3d_large + array_1d_add_large
print("Task 15\nSub-array with broadcasted addition:\n", broadcasted_sum_large)

# Task 16: Set the last column of a 2D array to the sum of the first two columns for each row using slicing and broadcasting
array_2d_set_last = np.arange(1, 17).reshape(4, 4)
array_2d_set_last[:, -1] = array_2d_set_last[:, 0] + array_2d_set_last[:, 1]
print("Task 16\nLast column set to sum of first two columns:\n", array_2d_set_last)

# Task 17: Extract a 2x2 sub-array starting from the element at position (1, 1)
array_2d = np.arange(36).reshape(6, 6)
sub_array_2x2 = array_2d[1:3, 1:3]
print("Task 17\n2x2 sub-array starting from (1, 1):\n", sub_array_2x2)

# Task 18: Extract all elements in the first two rows and all columns of the second slice along the third axis from a 3D array of shape (3, 2, 1)
array_3d = np.arange(6).reshape(3, 2, 1)
sub_array_3d = array_3d[:2, :, 0]
print("Task 18\nExtracted elements from 3D array:\n", sub_array_3d)

# Task 19: Use fancy indexing to extract elements at positions [1, 3, 4, 6] from an array of integers
array_int = np.arange(10)
fancy_indexed = array_int[[1, 3, 4, 6]]
print("Task 19\nElements at positions [1, 3, 4, 6]:\n", fancy_indexed)

# Task 20: Use fancy indexing to select rows [0, 2, 2] and columns [1, 3] from a 2D array
array_2d_fancy = np.arange(36).reshape(6, 6)
fancy_rows_cols = array_2d_fancy[[0, 2, 2], :][:, [1, 3]]
print("Task 20\nSelected rows [0, 2, 2] and columns [1, 3]:\n", fancy_rows_cols)

# Task 21: Extract all elements that are greater than 8 from a 1D array of random integers
random_integers = np.random.randint(0, 20, size=15)
greater_than_8 = random_integers[random_integers > 8]
print("Task 21\nElements greater than 8:\n", greater_than_8)

# Task 22: Replace all elements greater than 13 with the value 0 in a 2D array of shape (6, 6)
array_2d_replace = np.arange(36).reshape(6, 6)
array_2d_replace[array_2d_replace > 13] = 0
print("Task 22\nArray with elements > 13 replaced by 0:\n", array_2d_replace)

# Task 23: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)
array_2d_broadcast = np.ones((4, 3))
array_1d = np.array([1, 2, 3])
broadcasted_sum = array_2d_broadcast + array_1d
print("Task 23\nBroadcasted sum:\n", broadcasted_sum)

# Task 24: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
array_2d_mult = np.ones((3, 3)) * 2
array_1d_mult = np.array([1, 2, 3])
broadcasted_product = array_2d_mult * array_1d_mult
print("Task 24\nBroadcasted product:\n", broadcasted_product)


# Task 25: Perform element-wise addition of two 2D arrays of shapes (3, 1) and (1, 4)
array_2d_3x1 = np.array([[1], [2], [3]])
array_2d_1x4 = np.array([[4, 5, 6, 7]])
elementwise_sum = array_2d_3x1 + array_2d_1x4
print("Task 25\nElement-wise addition of arrays of shapes (3, 1) and (1, 4):\n", elementwise_sum)

# Task 26: Add a 2D array of shape (3, 4) to each 2D slice along the first axis of a 3D array of shape (2, 3, 4)
array_3d = np.ones((2, 3, 4))
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
broadcasted_sum_3d = array_3d + array_2d
print("Task 26\nBroadcasted sum on 3D array:\n", broadcasted_sum_3d)

# Task 27: Extract every second row and column from a 2D array, then add a 1D array to each row of the sliced array
array_2d_slice = np.arange(25).reshape(5, 5)
sliced_array = array_2d_slice[::2, ::2]
array_1d_add = np.array([1, 2, 3])
sliced_and_added = sliced_array + array_1d_add[:sliced_array.shape[1]]
print("Task 27\nEvery second row and column, added 1D array:\n", sliced_and_added)

# Task 28: Extract a sub-array from a 3D array and subtract a 2D array from each slice along the third axis using broadcasting
array_3d_slice = np.arange(24).reshape(4, 3, 2)
sub_array_3d_slice = array_3d_slice[:2, :, :]
array_2d_subtract = np.array([[1, 1], [2, 2], [3, 3]])
broadcasted_subtract = sub_array_3d_slice - array_2d_subtract[:, :, np.newaxis]
print("Task 28\nBroadcasted subtraction:\n", broadcasted_subtract)

# Task 29: Extract the diagonal elements from a 2D array and create a 1D array
array_2d_diag = np.arange(16).reshape(4, 4)
diagonal_elements = np.diag(array_2d_diag)
print("Task 29\nDiagonal elements:\n", diagonal_elements)

# Task 30: Reverse the order of elements in each row of a 2D array using slicing
array_2d_reverse = np.arange(16).reshape(4, 4)
reversed_array = array_2d_reverse[:, ::-1]
print("Task 30\nReversed rows:\n", reversed_array)

# Task 31: Extract a sub-array of shape (2, 3, 4) from a 3D array and add a 1D array of shape (4,) to each row along the third axis using broadcasting
array_3d_large = np.arange(210).reshape(7, 6, 5)
sub_array_3d_large = array_3d_large[:2, :3, :4]
array_1d_add_large = np.array([1, 2, 3, 4])
broadcasted_sum_large = sub_array_3d_large + array_1d_add_large
print("Task 31\nSub-array with broadcasted addition:\n", broadcasted_sum_large)

# Task 32: Set the last column of a 2D array to the sum of the first two columns for each row using slicing and broadcasting
array_2d_set_last = np.arange(1, 17).reshape(4, 4)
array_2d_set_last[:, -1] = array_2d_set_last[:, 0] + array_2d_set_last[:, 1]
print("Task 32\nLast column set to sum of first two columns:\n", array_2d_set_last)



Task 1
3x3 sub-array starting from (1,1):
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]
Task 2
Elements from first two rows, all columns of second slice:
 [[ 1  3  5]
 [ 7  9 11]]
Task 3
Elements at positions [1, 3, 4, 7]:
 [1 3 4 7]
Task 4
Rows [0, 2, 3] and columns [1, 3]:
 [[ 1  3]
 [11 13]
 [16 18]]
Task 5
Elements greater than 10:
 [18 15 11 16 14 16 14 16]
Task 6
Array with elements > 15 replaced by 0:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15  0  0  0  0]
 [ 0  0  0  0  0]]
Task 7
Broadcasted sum:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
Task 8
Broadcasted product:
 [[2. 4. 6.]
 [2. 4. 6.]
 [2. 4. 6.]]
Task 9
Element-wise addition:
 [[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]
Task 10
Broadcasted sum on 3D array:
 [[[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]

 [[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]]
Task 11
Every second row and column, added 1D array:
 [[ 1  4  7]
 [11 14 17]
 [21 24 27]]
Task 13
Diagonal elements:
 [ 0  5